default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: reservation_system_development

test:
  <<: *default
  database: reservation_system_test

production:
  <<: *default
  database: reservation_system_production
  username: reservation_system
  password: <%= ENV['RESERVATIONSYSTEM_DATABASE_PASSWORD'] %>